spring:
  application:
    name: youtube2document
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: llama-3.1-sonar-small-128k-online
          temperature: 0.7
      embedding:
        enabled: false


logging:
  level:
    ROOT: INFO

